### ISSUE TITLE
Group source into single

### ISSUE THREAD

**Issue by GoldenMouse** [logdna/logdna-agent-v2#13]
Bit of an odd question.  Currently each pod shows up as a separate "Source" under the GUI.  Is there a way to group them differently. Instead of per pod, let's say, per namespace? The reason is because pods gets recreated all the time (helm upgrades) and you end up with a bunch of PODNAME-####. 

I mean, look at this...

![image](https://user-images.githubusercontent.com/17915198/88251767-b2634b80-cc60-11ea-99cb-abe5b88d326d.png)

**Comment by jakedipity** [comment]
Thanks for the comment @GoldenMouse. You can try using the app instead to reference all the different pods:
<img width="1048" alt="Screen Shot 2020-07-22 at 10 04 35 PM" src="https://user-images.githubusercontent.com/29671917/88253622-68ca2f00-cc67-11ea-8aca-8b7c4dab6f1e.png">

If you want to filter by namespace you can use the following query instead (assuming they are in the `logdna-agent` namespace):
<img width="694" alt="Screen Shot 2020-07-22 at 10 06 00 PM" src="https://user-images.githubusercontent.com/29671917/88253672-8d260b80-cc67-11ea-904f-64a732dc0a6e.png">
```
namespace:logdna-agent
```

I'll also pass a note to our internal teams so we can look into making the UX experience more intuitive for kubernetes data

**Comment by GoldenMouse** [comment]
Yes no complaints of the app part.  Feels like Host should either be an instance node or k8s cluster and Pods should be a new header under Apps.  Thanks for looking into this!.
