### ISSUE TITLE
Enable Helm array index syntax 

### ISSUE THREAD

**Issue by keatz55** [logdna/logdna-agent-v2#131]
According to the Helm docs, we should be able to set array values in the following ways:

>As of Helm 2.5.0, it is possible to access list items using an array index syntax. For example, `--set servers[0].port=80` becomes:
>
>```yaml
>servers:
>  - port: 80
>```
> Multiple values can be set this way. The line `--set servers[0].port=80,servers[0].host=example` becomes:
>```yaml
>servers:
>  - port: 80
>    host: example
>```
https://helm.sh/docs/intro/using_helm/

I'm trying to do the following command via the logdna helm chart:
```shell
helm upgrade -n monitoring \
  --set logdna.key=$LOGDNA_INGESTION_KEY,logdna.tags=production \
  --set daemonset.tolerations[0].key=app,daemonset.tolerations[0].operator=Equal,daemonset.tolerations[0].value=api \
  logdna logdna/agent
```
However, I keep getting the following error:
```shell
no matches found: daemonset.tolerations[0].key=app
```

**Comment by jorgebay** [comment]
Hi @keatz55 !

I've tried myself and run into the same error...
With a little bit of digging I've found that, depending on your shell (I'm on `zsh`), an [escape char is needed for the brackets](https://github.com/helm/helm/issues/4508#issuecomment-582374867):

```
daemonset.tolerations\[0\].key=app
```

Instead of

```
daemonset.tolerations[0].key=app
```

In your case, it would be:

```shell
helm upgrade -n monitoring \
  --set logdna.key=$LOGDNA_INGESTION_KEY,logdna.tags=production \
  --set daemonset.tolerations\[0\].key=app,daemonset.tolerations\[0\].operator=Equal,daemonset.tolerations\[0\].value=api \
  logdna logdna/agent
```

We should submit a ticket/PR to the Helm docs to document it :)

**Comment by jorgebay** [comment]
I'm closing this one, feel free to reopen if you there are further issues w/ helm.
