### ISSUE TITLE
Override /var/log

### ISSUE THREAD

**Issue by GoldenMouse** [logdna/logdna-agent-v2#14]
According to docs, we can have the agent look at extra directories via `LOGDNA_LOG_DIRS` .  It would be nice if this totally overrides /var/log instead of appending to it.  Or have another way to not have /var/logs included.  I know there's `LOGDNA_EXCLUSION_RULE`.  But let's say I want to include /var/log/one_app and not /var/log.  Tricky to do at the moment.

**Comment by jakedipity** [comment]
I think the logic as is is currently borked for reasons you stated, but unfortunately we can't up and change it as third party vendors with multiple customers are already relying on the logic and it just isn't a priority for us at the moment.

Inclusion rules have a higher precedence than exclusion rules as seen in [`common/fs/src/rule.rs::Rules::passes`](https://github.com/logdna/logdna-agent-v2/blob/69142613ced50c8ffa084045f72a61d75ce1fe6f/common/fs/src/rule.rs#L73) which means you should be able to add `/var/log/**/*` as an exclusion rule but still include specific paths within `/var/log`.

**Comment by amit777** [comment]
in logdna-agent v1, the -f and -d flags don't seem to be implemented as they are described to be.  Also the appending of /var/log even if you delete it and then add some other directory seems like a not-so-pleasant bug.

**Comment by jorgebay** [comment]
I think we need to introduce a setting to allow overriding defaults (instead of appending to existing rules). By making override an opt-in feature we avoid breaking existing users.

**Comment by torkelrogstad** [comment]
I'm unable to exclude log files found in `/var/log`, even while setting, `var/log/**/*` as an exclusion rule. I absoluteley **DO NOT** want to ingest all files here, and that's seemingly impossible...

**Comment by dkhokhlov** [comment]
what is the agent agent version?  k8s?

**Comment by dkhokhlov** [comment]
About initial log dirs param:
- default value of initial log dirs is platform specific. it is "/var/log" on Linux.
- MZ_LOG_DIRS env var (or corresponding cli arg) only adds new log dirs. does not replace default.
- config file option log.dirs  does override the default
