### ISSUE TITLE
Add ARM support

### ISSUE THREAD

**Issue by mogggggg** [logdna/logdna-agent-v2#176]
Hi,
Not sure if this is the right repo to create this issue in but it would be great to have ARM support added to the `logdna/logdna-agent` Docker image. Cloud providers are pushing ARM quite heavily these days and we've had to build our own LogDNA image with multi-arch support using the old Node agent so we can continue using your product.

**Comment by jorgebay** [comment]
Good point @mogggggg !

Supporting ARM64 is high on our priority list.

I'll keep this open and ping you when it's scheduled to be released.

cc @mogggggg

**Comment by jorgebay** [comment]
cc @alfeng6

**Comment by mogggggg** [comment]
Hi @jorgebay, has there been any progress on this?

**Comment by odidev** [comment]
@jorgebay,  

[PR](https://github.com/logdna/logdna-agent-v2/pull/280) raised for adding arm64 support is merged but arm64 image is not yet released in dockerhub. 

May I know when are you planning to release arm64 image in dockerhub?

**Comment by jorgebay** [comment]
Maybe @alfeng6 @c-nixon can give more details about the arm64 support release plan.

**Comment by mogggggg** [comment]
Any update on this? It looks like support for ARM was added a while ago but still needs to be added to the CI config

**Comment by gjanco** [comment]
This is in the works now, @mogggggg.  We should be releasing it in the next week or two.

**Comment by rusrushal13** [comment]
Have it been released? :eyes:

**Comment by nodesocket** [comment]
Would ❤️  `arm64` support. Just tried installing the LogDNA agent on my Raspberry Pi Kubernetes cluster via Helm and failed with:

```
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by mogggggg** [comment]
> Has it been released? 👀 cc: @mogggggg

I'd say we're waiting for https://github.com/logdna/build-images/pull/26

**Comment by mogggggg** [comment]
@gjanco any update on when this is expected to be released?

**Comment by odidev** [comment]
May I know when are you planning to release arm64 image in dockerhub?

**Comment by c-nixon** [comment]
Hi, we hope to have them out with 3.5 which we plan to release a beta for in the next week or 2

**Comment by mogggggg** [comment]
I'll close this now since it's been released and we're using it 🎉
