### ISSUE TITLE
Container crashing with overflowed kernel queue

### ISSUE THREAD

**Issue by shaikatz** [logdna/logdna-agent-v2#200]
Hi,

Just moved from logdna agent v1 as process to a container, just to figure out the container crashes every few minutes as well due to:
```
[2021-08-17T08:49:29Z ERROR fs::cache] the inotify event queue has overflowed and events have presumably been lost
thread 'main' panicked at 'overflowed kernel queue', common/fs/src/cache/mod.rs:274:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looks like we are writing too many lines it finishes all the available space in the inotify event queue.
I saw similar issues on other logging agents, they had the option to change the mode from watching to polling files, maybe the logdna agent would allow that as well?

What's your recommendation to overcome that?

**Comment by teeohhem** [comment]
Hi thank you for the report. We are working on reproducing this and should have an update soon. Thank you!

**Comment by teeohhem** [comment]
cc @c-nixon

**Comment by c-nixon** [comment]
@shaikatz Just to keep you updated we have identified the cause of this issue and have a fix coming in our next release

**Comment by shaikatz** [comment]
Glad to hear, thank you.

**Comment by andreainnocenti** [comment]
Hi team, any news on this fix?

**Comment by c-nixon** [comment]
Hi @andreainnocenti  The fix is currently in the 3.4 beta release we released just before christmas if you want to try it out that would be great! We're gathering feedback before going GA to make sure we're definitely addressed the issue.

**Comment by andreainnocenti** [comment]
With the 3.4 beta release, no restarts after 5 days. We have multiple restarts every day with the version 3.3.

Do you know when the 3.4 will be promoted in GA?

**Comment by andreainnocenti** [comment]
any news?

**Comment by jzxg** [comment]
Hi @shaikatz, can you provide more detail on the nature of the fix? We are also hitting this intermittently with v3

**Comment by dkhokhlov** [comment]
[LogDNA Agent 3.4 (GA)](https://docs.logdna.com/changelog/logdna-agent-34-ga) has been released.
