### ISSUE TITLE
OOMKilled because of chart memory limit

### ISSUE THREAD

**Issue by luong-komorebi** [logdna/logdna-agent-v2#237]
I dont have the source code for Logdna Agent Helm Chart to refer to in this repository. Therefore, here are some of the steps to reproduce the problem:

1. Use `helm pull logdna/agent`. Optionally, `--untar` can be set to true so that the chart is downloaded to a folder
2. Open that folder, go to `values.yaml` file.

The default limit for memory is a bit underwhelming. I appreciate the ability to run logdna agent with minimal resources (as documented in here https://github.com/logdna/logdna-agent-v2/blame/master/docs/README.md#L258). However, inside the chart, the default limit is just 75Mi, which leaves logdna OOMKilled all the time (at least with our use-case)

Luckily we still have the ability to customise it without having to fork the chart, but setting a limit at 75Mi ruins the experience since following the steps over here (https://github.com/logdna/logdna-agent-v2/blob/master/docs/HELM.md) will never work if that values is not changed.

I propose changing it to `request`, instead of `limit`. Would love to make a pull request, but no source for the chart is available so I open this issue. Hopefully my concern makes sense

**Comment by jakedipity** [comment]
Per https://github.com/logdna/logdna-agent-v2#resource-limits, the memory limit is highly variable and dependent on your particular environment. An uncapped memory limit will probably not be desirable by most users so I don't think that it makes sense to remove it and just rely on the memory request parameter.

@c-nixon I see that in the above section it mentions that the agent requires at least 128 MiB, but the default in helm https://github.com/logdna/logdna-agent-v2/blob/master/docs/HELM.md#configuration is 75 MiB; can we bump that up to 128 MiB to at least be consistent?

**Comment by luong-komorebi** [comment]
Thanks for the feedback @jakedipity . I will close this issue since there are no further question or comment
