### ISSUE TITLE
Unusable for Kubernetes

### ISSUE THREAD

**Issue by johnkoehn** [logdna/logdna-agent-v2#365]
We've set up mezmo for our k8 cluster but the way the logs come in make it impossible to have views. Everytime we do a deployment, the source of the log gets updated. This causes us to have a crazy amount of sources with the values changing every deployment.
<img width="726" alt="Screen Shot 2022-07-05 at 3 03 58 PM" src="https://user-images.githubusercontent.com/6694825/177424746-7fe6a4ca-f478-4f10-b77e-6e0b464a4af3.png">

Is there a way we can control the host names or group these together?

**Comment by dkhokhlov** [comment]
there is a feature in the last agent release that allows metadata rewriting:
https://github.com/logdna/logdna-agent-v2/blob/master/docs/META.md
parsing of k8s metadata on backend side is complex. for example "file" metadata field is used to extract container attributes, which can be changed by LOGDNA_META_K8S_FILE value. the catch here is that the static value will affect all containers the same way. value of LOGDNA_META_K8S_FILE could refer to another fields, even k8s labels and annotations. it depends on what exactly you want to have in these line metadata fields.

**Comment by johnkoehn** [comment]
Ahh I see the complexity in this now.  Okay, this will help, thanks @dkhokhlov
