### ISSUE TITLE
Excluding namespaces and log files together

### ISSUE THREAD

**Issue by rudimk** [logdna/logdna-agent-v2#498]
Hello!

I'm facing a rather interesting issue whilst using `logdna-agent-v2` as a Helm chart on my EKS cluster. For context - EKS comes with its own CNI, which run as a `DawmonSet` and tends to log output towards two separate log files - `/host/var/log/aws-routed-eni/ipamd.log` and `/var/log/aws-routed-eni/plugin.log`. Logging for this workload is particular verbose, and it's just a lot of noise that tends to clog up our LogDNA views. In addition, there are certain namespaces whose logs we don't wish to grab at all. To that end, I've defined an exclusion rule like this:

```yaml
extraEnv:
  - name: LOGDNA_USE_K8S_LOG_ENRICHMENT
    value: "always"
  - name: LOGDNA_K8S_METADATA_LINE_EXCLUSION
    value: "namespace:cert-manager, namespace:kube-system, namespace:monitoring, namespace:porter-agent-system, label.app.kubernetes.io/instance:aws-vpc-cni"
```

I've verified that this config is being injected correctly into the LogDNA `DaemonSet`:

```
    Environment:
      LOGDNA_AGENT_KEY:                    <set to the key 'logdna-agent-key' in secret 'logdna-agent'>  Optional: false
      RUST_LOG:                            info
      POD_APP_LABEL:                        (v1:metadata.labels['app.kubernetes.io/name'])
      POD_NAME:                             (v1:metadata.name)
      NODE_NAME:                            (v1:spec.nodeName)
      NAMESPACE:                            (v1:metadata.namespace)
      LOGDNA_USE_K8S_LOG_ENRICHMENT:       always
      LOGDNA_K8S_METADATA_LINE_EXCLUSION:  namespace:cert-manager, namespace:kube-system, namespace:monitoring, namespace:porter-agent-system, label.app.kubernetes.io/instance:aws-vpc-cni
    Mounts:
```

Now the interesting part is that as far as the namespace exclusion's concerned, it works quite well - I'm not seeing logs from any of those namespaces. But the CNI logs keep appearing, since they're not being tailed from the `Pod`, but the log files I mentioned earlier. A sample dump from LogDNA:

```
Apr 28 12:39:03 whalesays-job-28044429-rx5cz sidecar waiting for job to start... 
Apr 28 12:39:03 ip-10-99-3-144 statistics.log 2023-04-28 07:09:03 169.254.169.123  1.532e-05 -1.035e-05  4.526e-06 -2.903e-08  4.327e-08 1.2e+00  64  23  22  0.00 
Apr 28 12:39:03 ip-10-99-3-144 tracking.log 2023-04-28 07:09:03 169.254.169.123  4     18.619      0.049 -1.035e-05 N  1  4.526e-06  9.612e-07  4.775e-04  2.668e-04  5.099e-04 
Apr 28 12:39:03 ip-10-99-3-144 measurements.log 2023-04-28 07:09:03 169.254.169.123 N  3 111 111 1111   4  4 1.00  2.785e-05  2.468e-04  6.199e-07  2.136e-04  2.747e-04 0A7FDC06 4B K K 
Apr 28 12:39:04 ip-10-99-2-129 ipamd.log {"level":"debug","ts":"2023-04-28T07:09:04.101Z","caller":"ipamd/ipamd.go:659","msg":"IP pool is too low: available (4) < ENI target (1) * addrsPerENI (5)"} 
Apr 28 12:39:04 ip-10-99-2-129 ipamd.log {"level":"debug","ts":"2023-04-28T07:09:04.101Z","caller":"ipamd/ipamd.go:2096","msg":"IP pool stats: Total IPs/Prefixes = 15/0, AssignedIPs/CooldownIPs: 11/0, c.maxIPsPerENI = 5"} 
Apr 28 12:39:04 ip-10-99-2-129 ipamd.log {"level":"debug","ts":"2023-04-28T07:09:04.101Z","caller":"ipamd/ipamd.go:660","msg":"Starting to increase pool size"} 
Apr 28 12:39:04 ip-10-99-2-129 ipamd.log {"level":"debug","ts":"2023-04-28T07:09:04.101Z","caller":"ipamd/ipamd.go:782","msg":"Node found \"ip-10-99-2-129.us-west-1.compute.internal\" - no of taints - 0"} 
Apr 28 12:39:04 ip-10-99-2-129 ipamd.log {"level":"debug","ts":"2023-04-28T07:09:04.101Z","caller":"ipamd/ipamd.go:660","msg":"Skipping ENI allocation as the max ENI limit of 3 is already reached (accounting for 0 unmanaged ENIs and 0 trunk ENIs)"} 
Apr 28 12:39:06 ip-10-99-2-129 statistics.log 2023-04-28 07:09:06 169.254.169.123  1.379e-05  2.815e-08  8.019e-06  1.100e-08  3.689e-07 8.1e-03  12   0   8  0.00 
Apr 28 12:39:06 ip-10-99-2-129 tracking.log 2023-04-28 07:09:06 169.254.169.123  4    -10.641      0.391  2.815e-08 N  1  8.019e-06 -2.442e-06  5.366e-04  2.656e-04  5.621e-04 
Apr 28 12:39:06 ip-10-99-2-129 measurements.log 2023-04-28 07:09:06 169.254.169.123 N  3 111 111 1111   4  4 0.97  3.138e-06  3.355e-04  6.151e-07  2.289e-04  2.594e-04 0A8E9682 4B K 
```

My theory's that although `aws-node`(the EKS CNI) runs inside the `kube-system` namespace, its use of separate log files on each node means that the agent elects to tail those files, inspite of the exclusion rule defined earlier. Is there a way to exclude these log files the way it used to work with the older agent, whilst also using the new namespace-based exclusion rules? Or am I missing something very basic here? Any pointers would be much appreciated!

**Comment by jakedipity** [comment]
@rudimk Your theory is correct, these particular logs aren't kubernetes logs and aren't able to be filtered by the `LOGDNA_K8S_METADATA_LINE_EXCLUSION` environment variable.

You can use `LOGDNA_EXCLUSION_RULES` which takes a glob pattern to exclude files you don't want. In your case, it might look something like
```
- name: LOGDNA_EXCLUSION_RULES
  value: /var/log/chrony/**, /var/log/aws-routed-eni/** 
```
_Note: The above will exlcude every file in `/var/log/chrony/` and `/var/log/aws-routed-eni/`, which may or may not be what you want._

**Comment by rudimk** [comment]
This works beautifully - just checked, and all those pesky logs are now being filtered out very nicely. Thanks ever so much, @jakedipity :)
