### ISSUE TITLE
Agent RPM Signing uses SHA-1

### ISSUE THREAD

**Issue by Delta-One-Two** [logdna/logdna-agent-v2#596]
Unable to install the agent on RHEL9.
 
RHEL9:
 
warning: Signature not supported. Hash algorithm SHA1 not available.
warning: Signature not supported. Hash algorithm SHA1 not available.
Problem opening package logdna-agent-3.9.1-1.x86_64.rpm
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: GPG check FAILED
[root@rhel9dev04 yum.repos.d]#

RHEL7:
 
Running transaction
  Installing : logdna-agent-3.9.1-1.x86_64                                                     1/1
  Verifying  : logdna-agent-3.9.1-1.x86_64                                                     1/1
 
Installed:
  logdna-agent.x86_64 0:3.9.1-1
 
Complete!
[root@rh7dev01 yum.repos.d]#

It works on RHEL7 because SHA1 is still there. This has been deprecated in RHEL9.

Now we could of course enable legacy keys, but this is _far_ from best practice, and we do not wish to make such actions standard operating procedure. 

Would it be possible to sign the RPM with a more up-to-date key?

Thanks!

**Comment by jakedipity** [comment]
We can look into updating our signing key to match current best practices. Thanks for the report @Delta-One-Two

**Comment by Delta-One-Two** [comment]
Thanks! That is greatly appreciated.

**Comment by jakedipity** [comment]
@Delta-One-Two We've recently updated our CI/CD pipeline to sign rpm packages with SHA256. Installing on RHEL9 should now work as expected. I'm closing this issue for now; feel free to re-open if you encounter any issues!
