### ISSUE TITLE
Collect logs from certain Pods or namespaces

### ISSUE THREAD

**Issue by nikoskip** [logdna/logdna-agent-v2#8]
Hi!

I just installed this agent a K8s cluster but I would like to know if I can configure it to only collect from certain Pods or namespace. Currently I'm seeing log's from certain K8s componentes like **kube-proxy** and others from Azure like **azure-vnet** or **azure-cnimonitor**.

I'm looking to share this tool with the dev team but I would like to avoid all this noise on the web app. I know I can create views and the devs could use them, but I think is better to avoid to collect this kind of log's.

Thanks!

**Comment by jakedipity** [comment]
Hi @nikoskip,

Currently the agent does not have the capability to select which pods or namespaces to listen to, but we might consider it for the future.

You can use exclusion rules to exclude logs that match any criteria you want:

**Settings (Cog Icon)** -> **Usage** -> **Exclusion Rules**

You can use the following query to exclude logs from the **kube-system** namespace or the pods **azure-vnet** and **azure-cnimonitor**:

```
namespace:kube-system OR pod:(azure-vnet azure-cnimonitor)
```
