### ISSUE TITLE
service account privileged

### ISSUE THREAD

**Issue by ac427** [logdna/logdna-agent-v2#80]
Trying to understand why logdna-agent require privileged access? 

`oc adm policy add-scc-to-user privileged system:serviceaccount:logdna-agent:logdna-agent`
https://github.com/logdna/logdna-agent#openshift-logging

Is there any kind of community slack or email group for these type of questions?

**Comment by sgwilson2674** [comment]
This has been resolved in the latest release of the k8s agent - see release notes here specifically the 'running as non-root' section : https://docs.logdna.com/changelog/logdna-agent-for-kubernetes-and-openshift-v3-0 

Closing this issue, but if you have additional questions, please open another issue and we'll be sure to respond.
