### ISSUE TITLE
Alpine Linux - Static linked build

### ISSUE THREAD

**Issue by yanivyalda** [logdna/logdna-agent-v2#9]
Does anyone know how to build this agent so all libraries are statically linked?

I've tried a few options but ldd on target/release/logdna-agent always returns dynamically linked libraries.

**Comment by jakedipity** [comment]
Hi @yanivyalda,

I'll look into trying to compile a statically linked version of the agent. I know there a couple issues with OpenSSL when using musl, but I haven't dived in a whole bunch yet. I'll update once I get a better idea of what's involved.

**Comment by yanivyalda** [comment]
@jakedipity thanks. I think I had the same issues when building. I tried adding 
OPENSSL_STATIC, OPENSSL_LIB_DIR and OPENSSL_INCLUDE_DIR but it didn't work.

I used these links as a reference https://github.com/naftulikay/rust-openssl-static-example, https://users.rust-lang.org/t/how-to-link-openssl-statically/14912

Still no luck.

**Comment by c-nixon** [comment]
@yanivyalda I don't know if you're still interested in this, but we now provide completely statically linked agent binaries for rpm and deb based distros, you should be able to run the binary on other systems if you unpack it from the deb
